# Generated by Django 5.1.7 on 2025-06-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
    ]
