# Generated by Django 5.1.7 on 2025-06-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
