# Generated by Django 5.2 on 2025-05-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck')], max_length=10)),
                ('brand', models.CharField(choices=[('toyota', 'Toyota'), ('honda', 'Honda'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('bmw', 'BMW')], max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('km', models.IntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented')], default='available', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
