# Generated by Django 5.1.7 on 2025-05-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicleclass_remove_vehicle_price_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
