# Generated by Django 5.1.7 on 2025-06-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('admin', 'Administrador'), ('secretary', 'Secretária'), ('manager', 'Gerente'), ('seller', 'Vendedor')], default='', max_length=20),
        ),
    ]
