# Generated by Django 5.1.7 on 2025-05-24 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_id_alter_vehicle_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='price_per_day',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicleclass'),
            preserve_default=False,
        ),
    ]
