# Generated by Django 5.1.7 on 2025-06-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(default='', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('rented', 'Alugado'), ('maintenance', 'Em Manutenção'), ('reserved', 'Reservado')], default='available', max_length=20),
        ),
    ]
