# Generated by Django 5.1.7 on 2025-07-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicle_plate_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('rented', 'Alugado'), ('reserved', 'Reservado'), ('maintenance', 'Manutenção')], default='available', max_length=20),
        ),
    ]
