# Generated by Django 5.1.7 on 2025-06-13 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_alter_client_phone'),
        ('vehicles', '0005_vehicle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('returned', 'Retornado'), ('canceled', 'Cancelado'), ('picked_up', 'Retirado')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_mileage', models.IntegerField(blank=True, null=True)),
                ('pickup_fuel_level', models.CharField(blank=True, max_length=20, null=True)),
                ('pickup_damage_notes', models.TextField(blank=True, null=True)),
                ('return_mileage', models.IntegerField(blank=True, null=True)),
                ('return_fuel_level', models.CharField(blank=True, max_length=20, null=True)),
                ('return_damage_notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicle')),
            ],
        ),
    ]
