# Generated by Django 5.1.7 on 2025-06-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('returned', 'Retornado'), ('canceled', 'Cancelado'), ('picked_up', 'Retirado')], max_length=20),
        ),
    ]
